apiVersion: v1
kind: Pod
metadata:
  name: test-with-labels
  namespace: demo-app
  labels:
    app: demo
    owner: akash
    env: dev
spec:
  containers:
  - name: test
    image: 910321623036.dkr.ecr.ap-south-1.amazonaws.com/platform/debug-tools:SIGNED_TAG
    command: ["sleep", "3600"]
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
