apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-signed-images-demo
spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: require-signed-by-github-actions
    match:
      resources:
        kinds:
        - Pod
        namespaces:
        - demo-app
    verifyImages:
    - imageReferences:
      - "910321623036.dkr.ecr.ap-south-1.amazonaws.com/platform/*"
      mutateDigest: false
      attestors:
      - entries:
        - keyless:
            issuer: "https://token.actions.githubusercontent.com"
            subject: "https://github.com/Akashoistec/secure-supply-chain-demo-app/.github/workflows/build-sign-push.yml@refs/heads/main"
